server:
  port: 8383
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:file:./camunda-h2-database
    username: demo
    password:
    driver-class: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  default-serialization-format: application/json