server:
  port: 8383
  servlet:
    context-path: /api

spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm:
  admin-user:
    id: demo
    password: demo
  default-serialization-format: application/json